on:
  workflow_call:
    inputs:
      environment:
        description: The GitHub environment to use
        type: string
        required: true
    secrets:
      ZIA_USERNAME:
        required: true
      ZIA_PASSWORD:
        required: true
      ZIA_API_KEY:
        required: true
      ZIA_CLOUD:
        required: true
      ZSCALER_SDK_TEST_SWEEP:
        required: true

jobs:
  zia-test-ubuntu:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ubuntu-go1.19-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
      - name: Run tests with retry on Ubuntu
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 10  # Adjust as needed
          command: |
            make test:integration:zia
            make ziaActivator
        env:
          ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
          ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
          ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
          ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
          ZSCALER_SDK_TEST_SWEEP: ${{ secrets.ZSCALER_SDK_TEST_SWEEP }}

  zia-test-macos:
    environment: ${{ inputs.environment }}
    runs-on: macos-latest
    needs: zia-test-ubuntu # This ensures the macos job only starts after the ubuntu job completes
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: macos-go1.20-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
      - name: Run tests with retry on MacOS
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 10  # Adjust as needed
          command: |
            make test:integration:zia
            make ziaActivator
        env:
          ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
          ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
          ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
          ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
          ZSCALER_SDK_TEST_SWEEP: ${{ secrets.ZSCALER_SDK_TEST_SWEEP }}
