on:
  workflow_call:
    inputs:
      environment:
        description: The GitHub environment to use
        type: string
        required: true
    secrets:
      ZDX_API_KEY_ID:
        required: true
      ZDX_API_SECRET:
        required: true

jobs:
  zdx-test:
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ matrix.go-version }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
      - name: Set Credentials
        env:
          ZDX_API_KEY_ID: ${{ secrets.ZDX_API_KEY_ID }}
          ZDX_API_SECRET: ${{ secrets.ZDX_API_SECRET }}
        run: |
          echo "script yet to be written "
